### ISSUE TITLE
在linux安装不成功是什么原因呢？

### ISSUE THREAD

**Issue by wunayou** [yanyiwu/nodejieba#100]
```
gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
gyp ERR! build error 
gyp ERR! stack Error: not found: make
gyp ERR! stack     at getNotFoundError (/root/.nvm/versions/node/v8.4.0/lib/node_modules/npm/node_modules/which/which.js:13:12)
gyp ERR! stack     at F (/root/.nvm/versions/node/v8.4.0/lib/node_modules/npm/node_modules/which/which.js:68:19)
gyp ERR! stack     at E (/root/.nvm/versions/node/v8.4.0/lib/node_modules/npm/node_modules/which/which.js:80:29)
gyp ERR! stack     at /root/.nvm/versions/node/v8.4.0/lib/node_modules/npm/node_modules/which/which.js:89:16
gyp ERR! stack     at /root/.nvm/versions/node/v8.4.0/lib/node_modules/npm/node_modules/which/node_modules/isexe/index.js:42:5
gyp ERR! stack     at /root/.nvm/versions/node/v8.4.0/lib/node_modules/npm/node_modules/which/node_modules/isexe/mode.js:8:5
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:152:21)
gyp ERR! System Linux 3.19.0-25-generic
gyp ERR! command "/root/.nvm/versions/node/v8.4.0/bin/node" "/root/.nvm/versions/node/v8.4.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /sever/node_modules/nodejieba
gyp ERR! node -v v8.4.0
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok 
npm WARN app@1.0.0 No description
npm WARN app@1.0.0 No repository field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! nodejieba@2.2.5 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the nodejieba@2.2.5 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2017-10-14T07_23_46_801Z-debug.log
```

**Comment by axetroy** [comment]
一样，windows下安装也不成功

**Comment by yanyiwu** [comment]
一般都是node版本原因，刚重跑了一下travis，可以参考 https://travis-ci.org/yanyiwu/nodejieba 这些成果的机器node版本和g++版本

**Comment by wunayou** [comment]
@axetroy 我忘 是怎么解决的了
