### ISSUE TITLE
Build error since node v10.0.0

### ISSUE THREAD

**Issue by Saren-Arterius** [yanyiwu/nodejieba#112]
I had to rebuild nodejieba since node upgraded, however I am not able to build nodejieba.

This can be reproduced using `node v10.0.0` and `npm v6.0.0` by performing `npm install nodejieba`.
```
> nodejieba@2.2.5 install /home/saren/sites/wtako.net/blog/node_modules/nodejieba
> node-gyp rebuild

make: Entering directory '/home/saren/sites/wtako.net/blog/node_modules/nodejieba/build'
  CXX(target) Release/obj.target/nodejieba/lib/index.o
In file included from ../../nan/nan.h:190:0,
                 from ../lib/utils.h:6,
                 from ../lib/nodejieba.h:4,
                 from ../lib/index.cpp:1:
../../nan/nan_maybe_43_inl.h: In function 'Nan::Maybe<bool> Nan::ForceSet(v8::Local<v8::Object>, v8::Local<v8::Value>, v8::Local<v8::Value>, v8::PropertyAttribute)':
../../nan/nan_maybe_43_inl.h:88:15: error: 'class v8::Object' has no member named 'ForceSet'
   return obj->ForceSet(GetCurrentContext(), key, value, attribs);
               ^~~~~~~~
In file included from ../lib/utils.h:6:0,
                 from ../lib/nodejieba.h:4,
                 from ../lib/index.cpp:1:
../../nan/nan.h: In function 'v8::Local<v8::Value> Nan::MakeCallback(v8::Local<v8::Object>, v8::Local<v8::Function>, int, v8::Local<v8::Value>*)':
../../nan/nan.h:817:60: warning: 'v8::Local<v8::Value> node::MakeCallback(v8::Isolate*, v8::Local<v8::Object>, v8::Local<v8::Function>, int, v8::Local<v8::Value>*)' is deprecated: Use MakeCallback(..., async_context) [-Wdeprecated-declarations]
         v8::Isolate::GetCurrent(), target, func, argc, argv);
                                                            ^
In file included from ../lib/utils.h:4:0,
                 from ../lib/nodejieba.h:4,
                 from ../lib/index.cpp:1:
/home/saren/.node-gyp/10.0.0/include/node/node.h:172:50: note: declared here
                 NODE_EXTERN v8::Local<v8::Value> MakeCallback(
                                                  ^
/home/saren/.node-gyp/10.0.0/include/node/node.h:88:42: note: in definition of macro 'NODE_DEPRECATED'
     __attribute__((deprecated(message))) declarator
                                          ^~~~~~~~~~
In file included from ../lib/utils.h:6:0,
                 from ../lib/nodejieba.h:4,
                 from ../lib/index.cpp:1:
../../nan/nan.h: In function 'v8::Local<v8::Value> Nan::MakeCallback(v8::Local<v8::Object>, v8::Local<v8::String>, int, v8::Local<v8::Value>*)':
../../nan/nan.h:831:62: warning: 'v8::Local<v8::Value> node::MakeCallback(v8::Isolate*, v8::Local<v8::Object>, v8::Local<v8::String>, int, v8::Local<v8::Value>*)' is deprecated: Use MakeCallback(..., async_context) [-Wdeprecated-declarations]
         v8::Isolate::GetCurrent(), target, symbol, argc, argv);
                                                              ^
In file included from ../lib/utils.h:4:0,
                 from ../lib/nodejieba.h:4,
                 from ../lib/index.cpp:1:
/home/saren/.node-gyp/10.0.0/include/node/node.h:165:50: note: declared here
                 NODE_EXTERN v8::Local<v8::Value> MakeCallback(
                                                  ^
/home/saren/.node-gyp/10.0.0/include/node/node.h:88:42: note: in definition of macro 'NODE_DEPRECATED'
     __attribute__((deprecated(message))) declarator
                                          ^~~~~~~~~~
In file included from ../lib/utils.h:6:0,
                 from ../lib/nodejieba.h:4,
                 from ../lib/index.cpp:1:
../../nan/nan.h: In function 'v8::Local<v8::Value> Nan::MakeCallback(v8::Local<v8::Object>, const char*, int, v8::Local<v8::Value>*)':
../../nan/nan.h:845:62: warning: 'v8::Local<v8::Value> node::MakeCallback(v8::Isolate*, v8::Local<v8::Object>, const char*, int, v8::Local<v8::Value>*)' is deprecated: Use MakeCallback(..., async_context) [-Wdeprecated-declarations]
         v8::Isolate::GetCurrent(), target, method, argc, argv);
                                                              ^
In file included from ../lib/utils.h:4:0,
                 from ../lib/nodejieba.h:4,
                 from ../lib/index.cpp:1:
/home/saren/.node-gyp/10.0.0/include/node/node.h:158:50: note: declared here
                 NODE_EXTERN v8::Local<v8::Value> MakeCallback(
                                                  ^
/home/saren/.node-gyp/10.0.0/include/node/node.h:88:42: note: in definition of macro 'NODE_DEPRECATED'
     __attribute__((deprecated(message))) declarator
                                          ^~~~~~~~~~
In file included from ../lib/utils.h:6:0,
                 from ../lib/nodejieba.h:4,
                 from ../lib/index.cpp:1:
../../nan/nan.h: In member function 'v8::Local<v8::Value> Nan::Callback::Call_(v8::Isolate*, v8::Local<v8::Object>, int, v8::Local<v8::Value>*) const':
../../nan/nan.h:1463:5: warning: 'v8::Local<v8::Value> node::MakeCallback(v8::Isolate*, v8::Local<v8::Object>, v8::Local<v8::Function>, int, v8::Local<v8::Value>*)' is deprecated: Use MakeCallback(..., async_context) [-Wdeprecated-declarations]
     ));
     ^
In file included from ../lib/utils.h:4:0,
                 from ../lib/nodejieba.h:4,
                 from ../lib/index.cpp:1:
/home/saren/.node-gyp/10.0.0/include/node/node.h:172:50: note: declared here
                 NODE_EXTERN v8::Local<v8::Value> MakeCallback(
                                                  ^
/home/saren/.node-gyp/10.0.0/include/node/node.h:88:42: note: in definition of macro 'NODE_DEPRECATED'
     __attribute__((deprecated(message))) declarator
                                          ^~~~~~~~~~
In file included from ../lib/nodejieba.h:4:0,
                 from ../lib/index.cpp:1:
../lib/utils.h: In function 'std::__cxx11::string ValueToString(v8::Local<v8::Value>)':
../lib/utils.h:56:27: warning: 'v8::String::Utf8Value::Utf8Value(v8::Local<v8::Value>)' is deprecated: Use Isolate version [-Wdeprecated-declarations]
   String::Utf8Value su(val);
                           ^
In file included from /home/saren/.node-gyp/10.0.0/include/node/v8.h:26:0,
                 from /home/saren/.node-gyp/10.0.0/include/node/node.h:63,
                 from ../lib/utils.h:4,
                 from ../lib/nodejieba.h:4,
                 from ../lib/index.cpp:1:
/home/saren/.node-gyp/10.0.0/include/node/v8.h:2822:28: note: declared here
                   explicit Utf8Value(Local<v8::Value> obj));
                            ^
/home/saren/.node-gyp/10.0.0/include/node/v8config.h:318:3: note: in definition of macro 'V8_DEPRECATED'
   declarator __attribute__((deprecated(message)))
   ^~~~~~~~~~
make: *** [nodejieba.target.mk:100: Release/obj.target/nodejieba/lib/index.o] Error 1
make: Leaving directory '/home/saren/sites/wtako.net/blog/node_modules/nodejieba/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/node-gyp/lib/build.js:258:23)
gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:225:12)
gyp ERR! System Linux 4.16.3-1-ARCH
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/saren/sites/wtako.net/blog/node_modules/nodejieba
gyp ERR! node -v v10.0.0
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok 
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! nodejieba@2.2.5 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the nodejieba@2.2.5 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/saren/.npm/_logs/2018-04-28T12_25_47_353Z-debug.log
```

**Comment by binarykitchen** [comment]
Still happens with Node.js v10.16.3, unable to build there.
