### ISSUE TITLE
运行错误

### ISSUE THREAD

**Issue by 1175969386** [yanyiwu/nodejieba#152]
internal/modules/cjs/loader.js:638
    throw err;
    ^

Error: Cannot find module 'C:\Users\RickLou\Desktop\jieba\node_modules\_nodejieba@2.4.0@nodejieba\build\Release\nodejieba.node'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (C:\Users\RickLou\Desktop\jieba\node_modules\_nodejieba@2.4.0@nodejieba\index.js:4:17)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)

这运行错误是怎么处理 重新装了好几遍都是这样子

**Comment by Brooooooklyn** [comment]
试一下 [@node-rs/jieba](https://github.com/Brooooooklyn/node-rs/tree/master/packages/jieba)
