### ISSUE TITLE
`GLIBCXX_3.4.20'  这个问题

### ISSUE THREAD

**Issue by wasfzxt** [yanyiwu/nodejieba#197]
发生在docker安装执行的时候，命令为：

docker run -it --network=host -v /Users/tmp:/tmp node:10.15 /bin/bash -c 'cd /tmp && npm install nodejieba --save'

-------------------------------------

运行时报错如下：
/lib64/libstdc++.so.6: version `GLIBCXX_3.4.20' not found (required by /opt/node_modules/nodejieba/build/Release/nodejieba.node)
   at Object.Module._extensions..node (internal/modules/cjs/loader.js:1208:18)
   at Module.load (internal/modules/cjs/loader.js:1002:32)
    at Function.Module._load (internal/modules/cjs/loader.js:901:14)
    at Module.require (internal/modules/cjs/loader.js:1044:19)
    at require (internal/modules/cjs/helpers.js:77:18)
    at Object.<anonymous> (/opt/node_modules/nodejieba/index.js:4:17)
    at Module._compile (internal/modules/cjs/loader.js:1158:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1178:10)
   at Module.load (internal/modules/cjs/loader.js:1002:32)
    at Function.Module._load (internal/modules/cjs/loader.js:901:14)

**Comment by Arnoldnuo** [comment]
咋解决的？
