### ISSUE TITLE
安装2.5.2失败

### ISSUE THREAD

**Issue by zwjtheone** [yanyiwu/nodejieba#225]
node-pre-gyp http GET https://github.com/yanyiwu/nodejieba/releases/download/v2.5.2/nodejieba-v2.5.2-node-v93-darwin-x64.tar.gz
node-pre-gyp ERR! install response status 404 Not Found on https://github.com/yanyiwu/nodejieba/releases/download/v2.5.2/nodejieba-v2.5.2-node-v93-darwin-x64.tar.gz 
node-pre-gyp WARN Pre-built binaries not installable for nodejieba@2.5.2 and node@16.20.0 (node-v93 ABI, unknown) (falling back to source compile with node-gyp) 
node-pre-gyp WARN Hit error response status 404 Not Found on https://github.com/yanyiwu/nodejieba/releases/download/v2.5.2/nodejieba-v2.5.2-node-v93-darwin-x64.tar.gz

**Comment by jiang-zx** [comment]
你这v93 哪来的

**Comment by mylady** [comment]
碰到一样的问题
node20.0.3版本要下载这个nodejieba-v2.5.2-node-v115-darwin-x64
release里没有

**Comment by TXHENG** [comment]
```
node-pre-gyp http GET https://github.com/yanyiwu/nodejieba/releases/download/v2.5.2/nodejieba-v2.5.2-node-v108-win32-x64.tar.gz
node-pre-gyp ERR! install response status 404 Not Found on https://github.com/yanyiwu/nodejieba/releases/download/v2.5.2/nodejieba-v2.5.2-node-v108-win32-x64.tar.gz
```

**Comment by showkawa** [comment]
> Node 18.16.1 版本
> 
> ```
> node-pre-gyp http GET https://github.com/yanyiwu/nodejieba/releases/download/v2.5.2/nodejieba-v2.5.2-node-v108-win32-x64.tar.gz
> node-pre-gyp ERR! install response status 404 Not Found on https://github.com/yanyiwu/nodejieba/releases/download/v2.5.2/nodejieba-v2.5.2-node-v108-win32-x64.tar.gz
> ```

the same issue with me in Node 18

**Comment by Mister-Hope** [comment]
请使用nodejs-jieba

**Comment by imnxg** [comment]
难道不支持Node.js 18吗
```
npm ERR! code ETARGET
npm ERR! notarget No matching version found for nodejs-jieba@2.5.2.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
```

**Comment by imnxg** [comment]
> 请使用nodejs-jieba

"vuepress-plugin-search-pro": "^2.0.0-rc.4",
我使用node.js V18.16.1 安装这个依赖nodejs-jieba，一直报错，请问有解决方法吗

**Comment by Mister-Hope** [comment]
nodejs-jieba 最新版应该是0.1.2

**Comment by Mister-Hope** [comment]
@yanyiwu Can you give me full access about your npm package? Or maybe deprecate yours with "No longer maintained for Node18+, please use nodes-joe a"?

**Comment by imnxg** [comment]
> @yanyiwu Can you give me full access about your npm package? Or maybe deprecate yours with "No longer maintained for Node18+, please use nodes-jieba"?

使用     "nodejs-jieba": "0.1.2"
报错如下：
```
  ⚡keney ❯❯ npm i
npm ERR! code 1
npm ERR! path D:\blogsource\weekly-vuepress\node_modules\nodejs-jieba
npm ERR! command failed
npm ERR! command C:\Windows\system32\cmd.exe /d /s /c node-pre-gyp install --fallback-to-build
npm ERR! Failed to execute 'D:\Program Files\nodejs\node.exe D:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js configure --fallback-to-build --module=D:\blogsource\weekly-vuepress\node_modules\nodejs-jieba\build\Release\jieba.node --module_name=jieba --module_path=D:\blogsource\weekly-vuepress\node_modules\nodejs-jieba\build\Release --napi_version=8 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v108' (1)
npm ERR! node-pre-gyp info it worked if it ends with ok
npm ERR! node-pre-gyp info using node-pre-gyp@1.0.11
npm ERR! node-pre-gyp info using node@18.16.1 | win32 | x64
npm ERR! node-pre-gyp info check checked for "D:\blogsource\weekly-vuepress\node_modules\nodejs-jieba\build\Release\jieba.node" (not found)
npm ERR! node-pre-gyp http GET https://github.com/Mister-Hope/nodejs-jieba/releases/download/v0.1.2/jieba-v0.1.2-node-v108-win32-x64.tar.gz
npm ERR! node-pre-gyp ERR! install request to https://github.com/Mister-Hope/nodejs-jieba/releases/download/v0.1.2/jieba-v0.1.2-node-v108-win32-x64.tar.gz failed, reason: Client network socket disconnected before secure TLS connection was established
npm ERR! node-pre-gyp WARN Pre-built binaries not installable for nodejs-jieba@0.1.2 and node@18.16.1 (node-v108 ABI, unknown) (falling back to source compile with node-gyp)
npm ERR! node-pre-gyp WARN Hit error request to https://github.com/Mister-Hope/nodejs-jieba/releases/download/v0.1.2/jieba-v0.1.2-node-v108-win32-x64.tar.gz failed, reason: Client network socket disconnected before secure TLS connection was established
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp info using node-gyp@9.3.1
npm ERR! gyp info using node@18.16.1 | win32 | x64
npm ERR! gyp info ok
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp info using node-gyp@9.3.1
npm ERR! gyp info using node@18.16.1 | win32 | x64
npm ERR! gyp info find Python using Python version 3.10.11 found at "C:\Users\keney\AppData\Local\Programs\Python\Python310\python.exe"
npm ERR! gyp ERR! find VS
npm ERR! gyp ERR! find VS msvs_version not set from command line or npm config
npm ERR! gyp ERR! find VS VCINSTALLDIR not set, not running in VS Command Prompt
npm ERR! gyp ERR! find VS could not use PowerShell to find Visual Studio 2017 or newer, try re-running with '--loglevel silly' for more details
npm ERR! gyp ERR! find VS looking for Visual Studio 2015
npm ERR! gyp ERR! find VS - not found
npm ERR! gyp ERR! find VS not looking for VS2013 as it is only supported up to Node.js 8
npm ERR! gyp ERR! find VS
npm ERR! gyp ERR! find VS **************************************************************
npm ERR! gyp ERR! find VS You need to install the latest version of Visual Studio
npm ERR! gyp ERR! find VS including the "Desktop development with C++" workload.
npm ERR! gyp ERR! find VS For more information consult the documentation at:
npm ERR! gyp ERR! find VS https://github.com/nodejs/node-gyp#on-windows
npm ERR! gyp ERR! find VS **************************************************************
npm ERR! gyp ERR! find VS
npm ERR! gyp ERR! configure error
npm ERR! gyp ERR! stack Error: Could not find any Visual Studio installation to use
npm ERR! gyp ERR! stack     at VisualStudioFinder.fail (D:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:122:47)
npm ERR! gyp ERR! stack     at D:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:75:16
npm ERR! gyp ERR! stack     at VisualStudioFinder.findVisualStudio2013 (D:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:369:14)
npm ERR! gyp ERR! stack     at D:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:71:14
npm ERR! gyp ERR! stack     at D:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:390:16
npm ERR! gyp ERR! stack     at D:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\util.js:54:7
npm ERR! gyp ERR! stack     at D:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\util.js:33:16
npm ERR! gyp ERR! stack     at ChildProcess.exithandler (node:child_process:427:5)
npm ERR! gyp ERR! stack     at ChildProcess.emit (node:events:513:28)
npm ERR! gyp ERR! stack     at maybeClose (node:internal/child_process:1091:16)
npm ERR! gyp ERR! System Windows_NT 10.0.19045
npm ERR! gyp ERR! command "D:\\Program Files\\nodejs\\node.exe" "D:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "configure" "--fallback-to-build" "--module=D:\\blogsource\\weekly-vuepress\\node_modules\\nodejs-jieba\\build\\Release\\jieba.node" "--module_name=jieba" "--module_path=D:\\blogsource\\weekly-vuepress\\node_modules\\nodejs-jieba\\build\\Release" "--napi_version=8" "--node_abi_napi=napi" "--napi_build_version=0" "--node_napi_label=node-v108"
npm ERR! gyp ERR! cwd D:\blogsource\weekly-vuepress\node_modules\nodejs-jieba
npm ERR! gyp ERR! node -v v18.16.1
npm ERR! gyp ERR! node-gyp -v v9.3.1
npm ERR! gyp ERR! not ok
npm ERR! node-pre-gyp ERR! build error
npm ERR! node-pre-gyp ERR! stack Error: Failed to execute 'D:\Program Files\nodejs\node.exe D:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js configure --fallback-to-build --module=D:\blogsource\weekly-vuepress\node_modules\nodejs-jieba\build\Release\jieba.node --module_name=jieba --module_path=D:\blogsource\weekly-vuepress\node_modules\nodejs-jieba\build\Release --napi_version=8 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v108' (1)
npm ERR! node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (D:\blogsource\weekly-vuepress\node_modules\@mapbox\node-pre-gyp\lib\util\compile.js:89:23)
npm ERR! node-pre-gyp ERR! stack     at ChildProcess.emit (node:events:513:28)
npm ERR! node-pre-gyp ERR! stack     at maybeClose (node:internal/child_process:1091:16)
npm ERR! node-pre-gyp ERR! stack     at ChildProcess._handle.onexit (node:internal/child_process:302:5)
npm ERR! node-pre-gyp ERR! System Windows_NT 10.0.19045
npm ERR! node-pre-gyp ERR! command "D:\\Program Files\\nodejs\\node.exe" "D:\\blogsource\\weekly-vuepress\\node_modules\\@mapbox\\node-pre-gyp\\bin\\node-pre-gyp" "install" "--fallback-to-build"
npm ERR! node-pre-gyp ERR! cwd D:\blogsource\weekly-vuepress\node_modules\nodejs-jieba
npm ERR! node-pre-gyp ERR! node -v v18.16.1
npm ERR! node-pre-gyp ERR! node-pre-gyp -v v1.0.11
npm ERR! node-pre-gyp ERR! not ok

npm ERR! A complete log of this run can be found in:
npm ERR!     D:\Program Files\nodejs\node_cache\_logs\2023-12-13T08_16_16_974Z-debug-0.log
```

**Comment by Mister-Hope** [comment]
This is because you can not access github to download assets and you cannot build the bin locally

**Comment by imnxg** [comment]
> This is because you can not access github to download assets and you cannot build the bin locally

github action 构建同样是报错，跟蹦迪应用
```
Run npm ci
npm ERR! code EUSAGE
npm ERR! 
npm ERR! `npm ci` can only install packages when your package.json and package-lock.json or npm-shrinkwrap.json are in sync. Please update your lock file with `npm install` before continuing.
npm ERR! 
npm ERR! Missing: nodejs-jieba@0.1.2 from lock file
npm ERR! Missing: @mapbox/node-pre-gyp@1.0.11 from lock file
npm ERR! Missing: node-addon-api@7.0.0 from lock file
npm ERR! Missing: node-gyp@10.0.1 from lock file
npm ERR! Missing: detect-libc@2.0.2 from lock file
npm ERR! Missing: https-proxy-agent@5.0.1 from lock file
npm ERR! Missing: make-dir@3.1.0 from lock file
npm ERR! Missing: node-fetch@2.7.0 from lock file
npm ERR! Missing: nopt@5.0.0 from lock file
npm ERR! Missing: npmlog@5.0.1 from lock file
npm ERR! Missing: rimraf@3.0.2 from lock file
npm ERR! Missing: tar@6.2.0 from lock file
npm ERR! Missing: agent-base@6.0.2 from lock file
npm ERR! Missing: semver@6.3.1 from lock file
npm ERR! Missing: whatwg-url@5.0.0 from lock file
npm ERR! Missing: env-paths@2.2.1 from lock file
npm ERR! Missing: exponential-backoff@3.1.1 from lock file
npm ERR! Missing: glob@10.3.10 from lock file
npm ERR! Missing: make-fetch-happen@13.0.0 from lock file
npm ERR! Missing: nopt@7.2.0 from lock file
npm ERR! Missing: proc-log@3.0.0 from lock file
npm ERR! Missing: which@[4](https://github.com/mynxg/weekly-vuepress/actions/runs/7197120573/job/19603516383#step:4:5).0.0 from lock file
npm ERR! Missing: @npmcli/agent@2.2.0 from lock file
npm ERR! Missing: cacache@18.0.1 from lock file
npm ERR! Missing: http-cache-semantics@4.1.1 from lock file
npm ERR! Missing: is-lambda@1.0.1 from lock file
npm ERR! Missing: minipass@7.0.4 from lock file
npm ERR! Missing: minipass-fetch@3.0.4 from lock file
npm ERR! Missing: minipass-flush@1.0.[5](https://github.com/mynxg/weekly-vuepress/actions/runs/7197120573/job/19603516383#step:4:6) from lock file
npm ERR! Missing: minipass-pipeline@1.2.4 from lock file
npm ERR! Missing: negotiator@0.[6](https://github.com/mynxg/weekly-vuepress/actions/runs/7197120573/job/19603516383#step:4:7).3 from lock file
npm ERR! Missing: promise-retry@2.0.1 from lock file
npm ERR! Missing: ssri@10.0.5 from lock file
npm ERR! Missing: agent-base@[7](https://github.com/mynxg/weekly-vuepress/actions/runs/7197120573/job/19603516383#step:4:8).1.0 from lock file
npm ERR! Missing: http-proxy-agent@7.0.0 from lock file
npm ERR! Missing: https-proxy-agent@7.0.2 from lock file
npm ERR! Missing: lru-cache@10.1.0 from lock file
npm ERR! Missing: socks-proxy-agent@[8](https://github.com/mynxg/weekly-vuepress/actions/runs/7197120573/job/19603516383#step:4:9).0.2 from lock file
npm ERR! Missing: @npmcli/fs@3.1.0 from lock file
npm ERR! Missing: fs-minipass@3.0.3 from lock file
npm ERR! Missing: glob@[10](https://github.com/mynxg/weekly-vuepress/actions/runs/7197120573/job/19603516383#step:4:11).3.10 from lock file
npm ERR! Missing: lru-cache@10.1.0 from lock file
```

**Comment by Mister-Hope** [comment]
that error means your lockfile is not compactable with package json, tbe errorclearlyshows.that nodejs-jieba and related plugings are missing.

delete your lockfile

**Comment by Mister-Hope** [comment]
this.is.not.how github issue shouldwork, go to web to find solutions, go to discussion panel  for help.

Posting in other's issue with your own question will bother all people in the thread

**Comment by iRecursion** [comment]
@imnxg  使用 "nodejs-jieba": "0.1.2"，要用梯子
不搞了，Node圈太乱，各种版本适配

**Comment by yanyiwu** [comment]
Please try using the latest version
please refer to https://github.com/yanyiwu/nodejieba-demo
