### ISSUE TITLE
请支持下 io.js 2.x

### ISSUE THREAD

**Issue by fundon** [yanyiwu/nodejieba#25]
```
]
  CXX(target) Release/obj.target/segment/src/segment.o
In file included from ../src/segment.cpp:1:
In file included from ../src/mix_segment.h:4:
In file included from ../src/utils.h:6:
In file included from ../node_modules/nan/nan.h:74:
In file included from ../node_modules/nan/nan_new.h:190:
../node_modules/nan/nan_implementation_12_inl.h:181:66: error: too many arguments to
      function call, expected at most 2, have 4
  return v8::Signature::New(v8::Isolate::GetCurrent(), receiver, argc, argv);
         ~~~~~~~~~~~~~~~~~~                                      ^~~~~~~~~~
/Users/fundon/.node-gyp/2.0.0/deps/v8/include/v8.h:4188:3: note: 'New' declared here
  static Local<Signature> New(
  ^
1 error generated.
make: *** [Release/obj.target/segment/src/segment.o] Error 1
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Users/fundon/.nvm/versions/io.js/v2.0.0/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:269:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:169:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1009:12)
gyp ERR! System Darwin 14.4.0
gyp ERR! command "/Users/fundon/.nvm/versions/io.js/v2.0.0/bin/iojs" "/Users/fundon/.nvm/versions/io.js/v2.0.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/fundon/dev/xxx/xyyy/node_modules/pinyin/node_modules/nodejieba
gyp ERR! node -v v2.0.0
gyp ERR! node-gyp -v v1.0.3
gyp ERR! not ok
npm info nodejieba@0.2.12 Failed to exec install script
npm ERR! Darwin 14.4.0
npm ERR! argv "/Users/fundon/.nvm/versions/io.js/v2.0.0/bin/iojs" "/Users/fundon/.nvm/versions/io.js/v2.0.0/bin/npm" "i" "pinyin@latest" "--save-dev" "-d"
npm ERR! node v2.0.0
npm ERR! npm  v2.9.0
npm ERR! code ELIFECYCLE

npm ERR! nodejieba@0.2.12 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the nodejieba@0.2.12 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the nodejieba package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls nodejieba
npm ERR! There is likely additional logging output above.
npm info preuninstall nodejieba@0.2.12

```

**Comment by yanyiwu** [comment]
谢谢提醒，在版本 v0.2.13 里已支持。

**Comment by fundon** [comment]
赞！
