### ISSUE TITLE
build problems osx/linux

### ISSUE THREAD

**Issue by davibe** [yanyiwu/nodejieba#35]
I am getting this on both OS X and linux. I am actually trying to build keystonejs where this is a dependency.

```
dade@choo:~/work/keystone(master)$ npm install nodejieba
\
> nodejieba@1.2.1 install /Users/dade/work/keystone/node_modules/nodejieba
> node-gyp rebuild

  CXX(target) Release/obj.target/nodejieba/lib/index.o
In file included from ../lib/index.cpp:1:
In file included from ../lib/nodejieba.h:4:
../lib/utils.h:17:11: error: use of undeclared identifier 'NanIntern'
  array = NanIntern::Factory<v8::Array>::New(ov.size());
          ^
../lib/utils.h:17:39: error: expected '(' for function-style cast or type construction
  array = NanIntern::Factory<v8::Array>::New(ov.size());
                             ~~~~~~~~~^
../lib/utils.h:17:42: error: no member named 'New' in the global namespace
  array = NanIntern::Factory<v8::Array>::New(ov.size());
                                       ~~^
../lib/utils.h:19:21: error: use of undeclared identifier 'NanIntern'
      array->Set(i, NanIntern::Factory<v8::String>::New(ov[i].c_str()));
                    ^
../lib/utils.h:19:50: error: expected '(' for function-style cast or type construction
      array->Set(i, NanIntern::Factory<v8::String>::New(ov[i].c_str()));
                                       ~~~~~~~~~~^
../lib/utils.h:19:53: error: no member named 'New' in the global namespace
      array->Set(i, NanIntern::Factory<v8::String>::New(ov[i].c_str()));
                                                  ~~^
../lib/utils.h:24:11: error: use of undeclared identifier 'NanIntern'
  array = NanIntern::Factory<v8::Array>::New(ov.size());
          ^
../lib/utils.h:24:39: error: expected '(' for function-style cast or type construction
  array = NanIntern::Factory<v8::Array>::New(ov.size());
                             ~~~~~~~~~^
../lib/utils.h:24:42: error: no member named 'New' in the global namespace
  array = NanIntern::Factory<v8::Array>::New(ov.size());
                                       ~~^
../lib/utils.h:30:19: error: use of undeclared identifier 'NanIntern'
    array->Set(i, NanIntern::Factory<v8::String>::New(ss.str().c_str()));
                  ^
../lib/utils.h:30:48: error: expected '(' for function-style cast or type construction
    array->Set(i, NanIntern::Factory<v8::String>::New(ss.str().c_str()));
                                     ~~~~~~~~~~^
../lib/utils.h:30:51: error: no member named 'New' in the global namespace
    array->Set(i, NanIntern::Factory<v8::String>::New(ss.str().c_str()));
                                                ~~^
../lib/utils.h:35:11: error: use of undeclared identifier 'NanIntern'
  array = NanIntern::Factory<v8::Array>::New(ov.size());
          ^
../lib/utils.h:35:39: error: expected '(' for function-style cast or type construction
  array = NanIntern::Factory<v8::Array>::New(ov.size());
                             ~~~~~~~~~^
../lib/utils.h:35:42: error: no member named 'New' in the global namespace
  array = NanIntern::Factory<v8::Array>::New(ov.size());
                                       ~~^
../lib/utils.h:41:19: error: use of undeclared identifier 'NanIntern'
    array->Set(i, NanIntern::Factory<v8::String>::New(ss.str().c_str()));
                  ^
../lib/utils.h:41:48: error: expected '(' for function-style cast or type construction
    array->Set(i, NanIntern::Factory<v8::String>::New(ss.str().c_str()));
                                     ~~~~~~~~~~^
../lib/utils.h:41:51: error: no member named 'New' in the global namespace
    array->Set(i, NanIntern::Factory<v8::String>::New(ss.str().c_str()));
                                                ~~^
18 errors generated.
make: *** [Release/obj.target/nodejieba/lib/index.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:269:23)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1074:12)
gyp ERR! System Darwin 14.4.0
gyp ERR! command "node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/dade/work/keystone/node_modules/nodejieba
gyp ERR! node -v v0.12.7
gyp ERR! node-gyp -v v2.0.1
gyp ERR! not ok 
npm ERR! Darwin 14.4.0
npm ERR! argv "node" "/usr/local/bin/npm" "install" "nodejieba"
npm ERR! node v0.12.7
npm ERR! npm  v2.12.1
npm ERR! code ELIFECYCLE

npm ERR! nodejieba@1.2.1 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the nodejieba@1.2.1 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the nodejieba package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls nodejieba
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/dade/work/keystone/npm-debug.log
dade@choo:~/work/keystone(master)$ 
```

**Comment by tylkomat** [comment]
In `package.json` the `^1.8.0` setting is not good it should be `~1.8.0` since `1.9.0` the structure of the classes was changed.

@davibe If you install `nan@~1.8.0` it compiles fine.

**Comment by yanyiwu** [comment]
`npm install nodejieba@1.2.2` to solve this problem

**Comment by yanyiwu** [comment]
Thank you @tylkomat
