### ISSUE TITLE
build error: Can't find "msbuild.exe". Do you have Microsoft Visual Studio C++ 2008+ installed?

### ISSUE THREAD

**Issue by cos800** [yanyiwu/nodejieba#47]
```
D:\sites\api>npm install

> nodejieba@1.4.6 install D:\sites\api\node_modules\nodejieba
> node-gyp rebuild


D:\sites\api\node_modules\nodejieba>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node  rebuild )
gyp ERR! build error
gyp ERR! stack Error: Can't find "msbuild.exe". Do you have Microsoft Visual Studio C++ 2008+ installed?
gyp ERR! stack     at findMsbuild (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:122:23)
gyp ERR! stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:104:11
gyp ERR! stack     at F (C:\Program Files\nodejs\node_modules\npm\node_modules\which\which.js:78:16)
gyp ERR! stack     at E (C:\Program Files\nodejs\node_modules\npm\node_modules\which\which.js:82:29)
gyp ERR! stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\which\which.js:93:16
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:82:15)
gyp ERR! System Windows_NT 5.2.3790
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd D:\sites\api\node_modules\nodejieba
gyp ERR! node -v v5.4.1
gyp ERR! node-gyp -v v3.0.3
gyp ERR! not ok
npm WARN install:nodejieba@1.4.6 nodejieba@1.4.6 install: `node-gyp rebuild`
npm WARN install:nodejieba@1.4.6 Exit status 1
npm WARN EPEERINVALID mongodb-core@1.2.32 requires a peer of kerberos@~0.0 but n
one was installed.
npm WARN EPEERINVALID mongodb-core@1.2.30 requires a peer of kerberos@~0.0 but n
one was installed.
```

可是我明明有装`Visual C++ 2008 SP1 Redistributable`

**Comment by cos800** [comment]
换cnpm装 还是一样：
```
D:\sites\api>cnpm install nodejieba
/
> nodejieba@1.4.6 install D:\sites\api\node_modules\nodejieba
> node-gyp rebuild


D:\sites\api\node_modules\nodejieba>if not defined npm_config_node_gyp (node "C:\Documents and Settings\Administrator\Application Data\npm\node_modules\cnpm\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node C:\Documents and Settings\Administrator\Application Data\npm\node_modules\cnpm\node_modules\node-gyp\bin\node-gyp.js rebuild )
module.js:327
    throw err;
    ^

Error: Cannot find module 'C:\Documents'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Function.Module.runMain (module.js:429:10)
    at startup (node.js:139:18)
    at node.js:999:3
 npm ERR! Windows_NT 5.2.3790
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Documents and Settings\\Administrator\\Application Data\\npm\\node_modules\\cnpm\\node_modules\\npm\\bin\\npm-cli.js" "--userconfig=C:\\Documents and Settings\\Administrator\\.cnpmrc" "--disturl=https://npm.taobao.org/mirrors/node" "--cache=C:\\Documents and Settings\\Administrator\\.cnpm" "--registry=https://registry.npm.taobao.org" "--node-gyp=C:\\Documents and Settings\\Administrator\\Application Data\\npm\\node_modules\\cnpm\\node_modules\\node-gyp\\bin\\node-gyp.js" "install" "nodejieba"
npm ERR! node v5.4.1
npm ERR! npm  v2.14.15
npm ERR! code ELIFECYCLE

npm ERR! nodejieba@1.4.6 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the nodejieba@1.4.6 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the nodejieba package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls nodejieba
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     D:\sites\api\npm-debug.log
```

**Comment by yanyiwu** [comment]
你好，谢谢你的反馈。
我今天也刚好开始在Windows上面折腾 Node.js(nodejieba) 
我确实也遇到问题了，但是我遇到的问题是：

```
MSBUILD : error MSB3428: 未能加载 Visual C++ 组件“VCBuild.exe”。要解决此问题，
1) 安装 .NET Fram
ework 2.0 SDK；2) 安装 Microsoft Visual Studio 2005；或 3) 如果将该组件安装到了
其他位置，请将其位置添加到系统
路径中。 [C:\Users\yanyiwu\node_modules\nodejieba\build\binding.sln]
```

我正在尝试安装个visual studio 2010 试图解决这个报错。等我装好了再回复你。

**Comment by cos800** [comment]
好的，谢谢~

**Comment by yanyiwu** [comment]
经别人验证，在win7或者win8下面使用 nodejieba@1.4.7 是可以通过的。
目测你这边应该是环境问题，你得自己查查啦。
我感觉node.js涉及到c++(node-gyp编译)的在windows上面搭环境就变得很复杂。

**Comment by cos800** [comment]
嗯 我本地win7也是可以的，但是服务器win2003不行。

**Comment by yanyiwu** [comment]
@cos800 哥们，原来win2003啊。那个时候好像 visual studio 都还没出吧。node-gyp 依赖 visual studio 啊。所以这个可能我帮不了你了啊。

**Comment by cos800** [comment]
好吧，算了，反正我早就打算把服务器系统给换了。。。
