### ISSUE TITLE
node4.2.2出现如下报错

### ISSUE THREAD

**Issue by HelloKevinTian** [yanyiwu/nodejieba#49]
Error: Module did not self-register.
    at Error (native)
    at Object.Module._extensions..node (module.js:460:18)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (/mnt/cs2/gameServer/node_modules/nodejieba/index.js:1:79)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)

**Comment by yanyiwu** [comment]
但是我在我的 ubuntu14.04里面使用 node4.2.1 使用nodejieba(1.4.9)一切正常啊。
能否贴一下你的机器信息，包括gcc版本？

**Comment by HelloKevinTian** [comment]
>> gcc -v
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/local/libexec/gcc/x86_64-unknown-linux-gnu/4.8.2/lto-wrapper
Target: x86_64-unknown-linux-gnu
Configured with: ../gcc-4.8.2/configure --enable-checking=release --enable-languages=c,c++ --disable-multilib
Thread model: posix
gcc version 4.8.2 (GCC)

>>cat  /etc/redhat-release
CentOS release 6.4 (Final)

-------------------------
是这样的  之前的nodejieba我是直接从别的档案copy进来的，后来我删掉重新执行 npm install nodejieba  问题就没有了。
