### ISSUE TITLE
引入的时候报错,提示版本不匹配

### ISSUE THREAD

**Issue by suwu150** [yanyiwu/nodejieba#94]
如下面所示,我是这样引入的:
```
const nodejieba = require('nodejieba');
// var result = nodejieba.cut("南京市长江大桥");
// console.log(result);
// //["南京市","长江大桥"]
```
结果报下面的错误:
```
module.js:435
  return process.dlopen(module, path._makeLong(filename));
                 ^

Error: Module version mismatch. Expected 46, got 48.
    at Error (native)
    at Object.Module._extensions..node (module.js:435:18)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
```

**Comment by yanyiwu** [comment]
提供一下 node,npm,node-gyp 的版本号

**Comment by suwu150** [comment]
Python 2.7.12
node-V: v6.9.4
npm-v: 3.10.10

**Comment by suwu150** [comment]
node-gyp -v
v3.6.0

**Comment by yanyiwu** [comment]
gcc 版本？可以参考下之前的issue，https://github.com/yanyiwu/nodejieba/issues?q=is%3Aissue+is%3Aclosed 好多因为环境问题没装上，后来都是通过修复环境问题装上的。

**Comment by suwu150** [comment]
好的,我试试,谢了

**Comment by suwu150** [comment]
还是不行,不是gcc的问题吧,我`npm i nodejieba --save-dev ` 的时候是没有报错的
