### ISSUE TITLE
node 6.10.1 下无法安装

### ISSUE THREAD

**Issue by JohnnieFucker** [yanyiwu/nodejieba#95]
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/etc/node/lib/node_modules/cnpm/node_modules/node-gyp/lib/build.js:258:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Linux 2.6.32-642.13.1.el6.x86_64
gyp ERR! command "/etc/node/bin/node" "/etc/node/lib/node_modules/cnpm/node_modules/npminstall/node-gyp-bin/node-gyp.js" "rebuild"
gyp ERR! cwd /data/www/htdocs/ai_weixin/node_modules/_nodejieba@2.2.5@nodejieba
gyp ERR! node -v v6.10.1
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok 
Install fail! Error: Run "sh -c node-gyp rebuild" error, exit code 1

**Comment by JohnnieFucker** [comment]
发现是服务器g++版本问题，需要g++4.8以上。
